stages:
  - lint
  - test
  - security

image: debian:latest

before_script:
  - apt-get update && apt-get install -y shellcheck

linting:
  stage: lint
  script:
    - shellcheck scripts/install.sh

testing:
  stage: test
  script:
    - bash tests/test_install.sh

security_scan:
  stage: security
  script:
    - echo "Ejecutando escaneo basico contra repositorios públicos de configs"
    - grep -irq "password=" configs/ || echo "No se han encontrado secretos filtrados hardcodeados."
